 # 언어(플랫폼)를 고른다.
language: android

# Avoid this error : ./gradlew: Permission denied > The command "./gradlew build connectedCheck" exited with 126.
before_install:
  - chmod +x gradlew

android:
  components:
      # SDK Tools 중에 무얼 빌드할지 선택가능하다
      - tools
      # build tools 를 선택가능하다. 여기선 디폴트 19.1.0 으로 설정,
      # 여러개 설정하려면 두개설정하면된다.
      - build-tools-25.0.3
      # android api버전을 선택가능하다. 이또한 여러개 가능
      - android-25
      - android-15
      # 추가 컴포넌트 설정
      -  extra-google-google_play_services
      # emulater로 테스트도 가능
      -  sys-img-armeabi-v7a-android-25
      -  sys-img-x86-android-25
jdk: # 아래와 같이 java version / jdk 종류도 선택가능
  - oraclejdk8

