language: android 
jdk: oraclejdk8

  before_install: 
  - chmod +x gradlew  

android: 
  components: 
      - tools 
      - platform-tools 
      - tools 
      - build-tools-25.0.2 
      - android-25 
      - extra-google-google_play_services 
      - extra-android-m2repository  

install: 
      - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" 
      - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

  script: 
  - ./gradlew clean build -x lint